version: '3.8'

services:
  python3:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'python3'
    restart: always
    tty: true
    volumes:
      - .:/usr/src/app
volumes:
  python3:
    driver: local
